"""baseline 테이블 컬럼 수정

Revision ID: fced1946bdd9
Revises: 43ac8fbbc883
Create Date: 2025-11-27 19:11:03.337968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'fced1946bdd9'
down_revision: Union[str, Sequence[str], None] = '43ac8fbbc883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasetbaseline', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('datasetbaseline', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_datasetbaseline_dataset_id'), 'datasetbaseline', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasetbaseline_dataset_id'), table_name='datasetbaseline')
    op.drop_column('datasetbaseline', 'updated_at')
    op.drop_column('datasetbaseline', 'created_at')
    # ### end Alembic commands ###
